### ISSUE TITLE
how to get qmf.dat file?

### ISSUE THREAD

**Issue by maozhiqiang** [TUIlmenauAMS/FilterBanks_PythonKerasNeuralNetworkImplemention#1]
Hi @gdtschuller , thanks for this great repo.
   how to get qmf.dat 
thanks
    mao

**Comment by gdtschuller** [comment]
Thank you. The file should be in the same directory.
Many greetings,
 Gerald Schuller

**Comment by maozhiqiang** [comment]
@gdtschuller I mean, how to calculate this file！ 
thanks!
 mao

**Comment by gdtschuller** [comment]
Aha, good point. It is optained by optimization. See examples and details in:
https://github.com/TUIlmenauAMS/Jupyter_notebooks_AMS/tree/master/Audio_Coding/Lec7_PQMF
and:
https://www.tu-ilmenau.de/fileadmin/public/mt_ams/Audio_Coding/Vorlesung/WS_2017-18/07_shl_PQMF_MPEG1-2BC_WS2017-18.pdf
Many greetings,
  Gerald Schuller
